In [262]:
! nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


In [263]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


**Learning about tensors**

In [264]:
scalar = torch.tensor(9)
scalar

tensor(9)

In [265]:
scalar.ndim

0

In [266]:
scalar.shape

torch.Size([])

In [267]:
vector = torch.tensor([1,2,3,4])
vector

tensor([1, 2, 3, 4])

In [268]:
vector.ndim

1

In [269]:
vector.shape

torch.Size([4])

In [270]:
MATRIX = torch.tensor([[3,1],[2,4],[5,0],[6,7]])
MATRIX

tensor([[3, 1],
        [2, 4],
        [5, 0],
        [6, 7]])

In [271]:
MATRIX.ndim

2

In [272]:
MATRIX.shape

torch.Size([4, 2])

In [273]:
TENSOR = torch.tensor([[[[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]]],[[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]]]]])
TENSOR

tensor([[[[[1, 2, 3],
           [4, 5, 6],
           [7, 8, 9]],

          [[1, 2, 3],
           [4, 5, 6],
           [7, 8, 9]]],


         [[[1, 2, 3],
           [4, 5, 6],
           [7, 8, 9]],

          [[1, 2, 3],
           [4, 5, 6],
           [7, 8, 9]]]]])

In [274]:
TENSOR.ndim

5

In [275]:
TENSOR.shape

torch.Size([1, 2, 2, 3, 3])

In [276]:
# The number of sqaure bracket pair at first corresponidng to that at last (they will be highest in number) and correspond to the dimension of the tensor
# To every dimension corresponds to a shape , logic of which is based on comma seperated values and square brackets.

In [277]:
# Construct a tensor of shape (2,3,2,5) , step by step
TENSOR = torch.tensor([[1,1,1,1,1],[1,1,1,1,1]])
TENSOR.shape

torch.Size([2, 5])

In [278]:
TENSOR = torch.tensor([[[1,1,1,1,1],[1,1,1,1,1]],[[1,1,1,1,1],[1,1,1,1,1]],[[1,1,1,1,1],[1,1,1,1,1]]])
TENSOR.shape

torch.Size([3, 2, 5])

In [279]:
TENSOR = torch.tensor([[[[1,1,1,1,1],[1,1,1,1,1]],[[1,1,1,1,1],[1,1,1,1,1]],[[1,1,1,1,1],[1,1,1,1,1]]],[[[1,1,1,1,1],[1,1,1,1,1]],[[1,1,1,1,1],[1,1,1,1,1]],[[1,1,1,1,1],[1,1,1,1,1]]]])
TENSOR.shape

torch.Size([2, 3, 2, 5])

In [280]:
TENSOR

tensor([[[[1, 1, 1, 1, 1],
          [1, 1, 1, 1, 1]],

         [[1, 1, 1, 1, 1],
          [1, 1, 1, 1, 1]],

         [[1, 1, 1, 1, 1],
          [1, 1, 1, 1, 1]]],


        [[[1, 1, 1, 1, 1],
          [1, 1, 1, 1, 1]],

         [[1, 1, 1, 1, 1],
          [1, 1, 1, 1, 1]],

         [[1, 1, 1, 1, 1],
          [1, 1, 1, 1, 1]]]])

In [281]:
long_tensor = torch.arange(1, 2**5 + 1, dtype=torch.long).reshape(2, 2, 2, 2, 2)

print(long_tensor) # This is (2,2,2,2,2) shape tensor

tensor([[[[[ 1,  2],
           [ 3,  4]],

          [[ 5,  6],
           [ 7,  8]]],


         [[[ 9, 10],
           [11, 12]],

          [[13, 14],
           [15, 16]]]],



        [[[[17, 18],
           [19, 20]],

          [[21, 22],
           [23, 24]]],


         [[[25, 26],
           [27, 28]],

          [[29, 30],
           [31, 32]]]]])


In [282]:
long_tensor.shape

torch.Size([2, 2, 2, 2, 2])

In [283]:
# Access 24
long_tensor[1][0][1][1][1]

tensor(24)

In [284]:
# In shape the 0th index corresponds to highest sq bracket and last index corresponds to scalers present in one pair of sq bracket [].

In [285]:
# tensor shape (3,224,224) - [[[1,1,.....224],[1,1,.....224]....... 224]],[[1,1,.....224],[1,1,.....224],[1,1,.....224].......224]],[[1,1,.....224],[1,1,.....224]...........224]]]

In [286]:
# To fetch single item from a tensor
x = torch.tensor(1)
x.item()

1

**Random Tensors**

In [287]:
# Random Tensor
torch.rand(4,4)

tensor([[0.4318, 0.4078, 0.3224, 0.7408],
        [0.7730, 0.7708, 0.7673, 0.9595],
        [0.6836, 0.6906, 0.9440, 0.6093],
        [0.4180, 0.0040, 0.0114, 0.2454]])

In [288]:
x = torch.rand(3,224,224)

In [289]:
y = torch.rand(224,224,3)

In [290]:
x.shape

torch.Size([3, 224, 224])

In [291]:
y.shape

torch.Size([224, 224, 3])

In [292]:
x.ndim

3

In [293]:
y.ndim

3

In [294]:
x

tensor([[[0.4882, 0.5544, 0.8100,  ..., 0.5117, 0.6969, 0.5971],
         [0.9649, 0.8254, 0.2365,  ..., 0.1605, 0.5538, 0.8629],
         [0.8437, 0.9670, 0.0119,  ..., 0.8576, 0.9341, 0.3329],
         ...,
         [0.4264, 0.6988, 0.8864,  ..., 0.7425, 0.4719, 0.3662],
         [0.6174, 0.0940, 0.5256,  ..., 0.6268, 0.7652, 0.8626],
         [0.3348, 0.2294, 0.3055,  ..., 0.7323, 0.2592, 0.8807]],

        [[0.1384, 0.4593, 0.5274,  ..., 0.1854, 0.7141, 0.2492],
         [0.4447, 0.5815, 0.8517,  ..., 0.3110, 0.0621, 0.7833],
         [0.4663, 0.4661, 0.5897,  ..., 0.2358, 0.7307, 0.4859],
         ...,
         [0.9113, 0.1853, 0.1536,  ..., 0.5148, 0.8019, 0.0823],
         [0.5464, 0.4962, 0.3416,  ..., 0.5495, 0.9629, 0.6521],
         [0.9446, 0.2243, 0.1175,  ..., 0.7973, 0.0495, 0.8444]],

        [[0.6528, 0.0278, 0.7328,  ..., 0.4301, 0.7482, 0.9345],
         [0.0825, 0.3372, 0.3036,  ..., 0.0166, 0.5163, 0.0842],
         [0.0979, 0.3193, 0.3515,  ..., 0.1698, 0.2514, 0.

In [295]:
y

tensor([[[0.0354, 0.1926, 0.1746],
         [0.3552, 0.1228, 0.2126],
         [0.6673, 0.7482, 0.5106],
         ...,
         [0.3022, 0.7069, 0.9493],
         [0.0689, 0.3427, 0.4325],
         [0.2173, 0.0044, 0.7066]],

        [[0.1448, 0.6636, 0.3360],
         [0.7173, 0.3597, 0.7988],
         [0.1203, 0.5260, 0.9898],
         ...,
         [0.6111, 0.0143, 0.3447],
         [0.7950, 0.4898, 0.9403],
         [0.0262, 0.7709, 0.1274]],

        [[0.8414, 0.2946, 0.2297],
         [0.5611, 0.7261, 0.5117],
         [0.1417, 0.6309, 0.5461],
         ...,
         [0.5559, 0.9924, 0.5042],
         [0.0184, 0.2624, 0.0458],
         [0.3774, 0.6381, 0.1980]],

        ...,

        [[0.1853, 0.1780, 0.5479],
         [0.4328, 0.2643, 0.1761],
         [0.5525, 0.9643, 0.0449],
         ...,
         [0.5102, 0.7575, 0.0249],
         [0.7919, 0.1360, 0.4395],
         [0.6062, 0.8844, 0.7000]],

        [[0.4433, 0.6560, 0.3065],
         [0.8848, 0.4823, 0.9382],
         [0.

**Tesnor of zeros and one**



In [296]:
torch.zeros(3,4)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [297]:
torch.ones(3,4)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

**arange and tensor like**

In [298]:
# In arange start , end , step are the arguments
x = torch.arange(3,100,6)
x

tensor([ 3,  9, 15, 21, 27, 33, 39, 45, 51, 57, 63, 69, 75, 81, 87, 93, 99])

In [299]:
# torch.zeros_like(input) , it will create tensor with same size as input
tensor = torch.empty(4,6)
torch.zeros_like(tensor)

tensor([[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]])

In [300]:
tensor

tensor([[ 0.0000e+00,  0.0000e+00, -2.9609e-11,  3.1491e-41, -2.8375e-12,
          3.1491e-41],
        [-2.1615e-33,  4.5719e-41,  0.0000e+00,  0.0000e+00,  0.0000e+00,
          0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
          0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  1.4013e-45,  0.0000e+00,  0.0000e+00,
          0.0000e+00]])

**Tensor has 3 arguments in it , dtype - for data type , device like cuda or "cpu" , requires_grad to check gradients.**

The Default datatype for tensor is float32

In [301]:
tensor = torch.zeros(3,4)
tensor.dtype # default

torch.float32

In [302]:
tensor = torch.zeros(3,4, dtype=torch.float16)
tensor.dtype

torch.float16

In [303]:
# Using type function
tensor_1 = tensor.type(torch.int16)
tensor_1

tensor([[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]], dtype=torch.int16)

In [304]:
x = torch.rand(3,4)
x

tensor([[0.3700, 0.4079, 0.5283, 0.2411],
        [0.8577, 0.2081, 0.1457, 0.2165],
        [0.6897, 0.7573, 0.6393, 0.2684]])

In [305]:
x.dtype

torch.float32

In [306]:
y = x.type(torch.int64) # the data type gets converted to the argument written inside type and tensor remains same.

In [307]:
y

tensor([[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]])

The 3 most common errors seen in while coding pytorch via tensors
1. Tensors not right data type
2. Tensors not right shape
3. Tensors not on right device.

In [308]:
tensor = torch.rand(3,4) #Gattering info of the most imp thing from tensors
print(f"The datatype of tensor is {tensor.dtype}")
print(f"The shape of tensor is {tensor.shape}")
print(f"The device of tensor is {tensor.device}")


The datatype of tensor is torch.float32
The shape of tensor is torch.Size([3, 4])
The device of tensor is cpu


## Manipulating tensors (tensor operations)

In deep learning, data (images, text, video, audio, protein structures, etc) gets represented as tensors.

A model learns by investigating those tensors and performing a series of operations (could be 1,000,000s+) on tensors to create a representation of the patterns in the input data.

These operations are often a wonderful dance between:
* Addition
* Substraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

In [309]:
tensor = torch.rand(3,4)
tensor

tensor([[0.5510, 0.1298, 0.4707, 0.9479],
        [0.7727, 0.3618, 0.0619, 0.9691],
        [0.7939, 0.9154, 0.7615, 0.7594]])

In [310]:
print(f"Result of tensor + 10 - {tensor + 10}")
print(f"\n Result of tensor.add(tensor,10) - {torch.add(tensor,10)}\n") # same like above alternative command
# Like that
print(tensor*10)

Result of tensor + 10 - tensor([[10.5510, 10.1298, 10.4707, 10.9479],
        [10.7727, 10.3618, 10.0619, 10.9691],
        [10.7939, 10.9154, 10.7615, 10.7594]])

 Result of tensor.add(tensor,10) - tensor([[10.5510, 10.1298, 10.4707, 10.9479],
        [10.7727, 10.3618, 10.0619, 10.9691],
        [10.7939, 10.9154, 10.7615, 10.7594]])

tensor([[5.5099, 1.2980, 4.7068, 9.4787],
        [7.7272, 3.6183, 0.6189, 9.6906],
        [7.9392, 9.1540, 7.6146, 7.5944]])


In [311]:
# Matrix Multiplication is main thing , Matrix is 2 dimentional tensor , torch.mm or torch.matmul and @ is used for Matrix Multiplication.

In [312]:
# We can write the code for matrix multiplication by hands on by for loop but it's not reccommended , coz pytorch used it's optimal vectorization in matrix multiplication in matmul.

In [313]:
# Create a tensor of random integers with shape (3, 2) and dtype int32
tensor_A = torch.randint(0, 10, (3, 2), dtype=torch.int32)

# Create a tensor of random floats with shape (3, 2) and convert to int32
tensor_B = torch.randint(0, 10, (3, 2), dtype=torch.int32)

print(f"Tensor A:\n{tensor_A}\n")
print(f"Tensor B:\n{tensor_B}\n")

Tensor A:
tensor([[9, 9],
        [9, 8],
        [2, 2]], dtype=torch.int32)

Tensor B:
tensor([[2, 8],
        [8, 6],
        [3, 8]], dtype=torch.int32)



In [314]:
tensor_B.T # Taking transpose applying .T to the matrix

tensor([[2, 8, 3],
        [8, 6, 8]], dtype=torch.int32)

In [315]:
torch.matmul(tensor_A,tensor_B.T)

tensor([[ 90, 126,  99],
        [ 82, 120,  91],
        [ 20,  28,  22]], dtype=torch.int32)

In [316]:
# The operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}\n")
print(f"New shapes: tensor_A = {tensor_A.shape} (same as above), tensor_B.T = {tensor_B.T.shape}\n")
print(f"Multiplying: {tensor_A.shape} * {tensor_B.T.shape} <- inner dimensions match\n")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])

New shapes: tensor_A = torch.Size([3, 2]) (same as above), tensor_B.T = torch.Size([2, 3])

Multiplying: torch.Size([3, 2]) * torch.Size([2, 3]) <- inner dimensions match

Output:

tensor([[ 90, 126,  99],
        [ 82, 120,  91],
        [ 20,  28,  22]], dtype=torch.int32)

Output shape: torch.Size([3, 3])


In [317]:
# Finding min max sum mean in tensor
x = torch.arange(0,100,10)
print(f"{x}\n")
print(f"max value is {x.max()} and can also be fed from torch.max(x) which gives {torch.max(x)}")
print(f"min value is {x.min()}")
print(f"mean value is {x.type(torch.float32).mean()}")  # The error of not right data type came up , the mean doesn't get applied to int 64 , Longint dtype
print(f"sum value is {x.sum()}")

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

max value is 90 and can also be fed from torch.max(x) which gives 90
min value is 0
mean value is 45.0
sum value is 450


In [318]:
y = torch.rand(2,3)
y

tensor([[0.1441, 0.3401, 0.6634],
        [0.0210, 0.2901, 0.4719]])

In [319]:
torch.mean(y)

tensor(0.3218)

In [320]:
# Finding the position or index that is argmin() , argmax() to find where does it occur
y.argmax()

tensor(2)

In [321]:
y.argmin()

tensor(3)

### Reshaping, stacking, squeezing and unsqueezing

Often times you'll want to reshape or change the dimensions of your tensors without actually changing the values inside them.

To do so, some popular methods are:

| Method | One-line description |
| ----- | ----- |
| [`torch.reshape(input, shape)`](https://pytorch.org/docs/stable/generated/torch.reshape.html#torch.reshape) | Reshapes `input` to `shape` (if compatible), can also use `torch.Tensor.reshape()`. |
| [`Tensor.view(shape)`](https://pytorch.org/docs/stable/generated/torch.Tensor.view.html) | Returns a view of the original tensor in a different `shape` but shares the same data as the original tensor. |
| [`torch.stack(tensors, dim=0)`](https://pytorch.org/docs/1.9.1/generated/torch.stack.html) | Concatenates a sequence of `tensors` along a new dimension (`dim`), all `tensors` must be same size. |
| [`torch.squeeze(input)`](https://pytorch.org/docs/stable/generated/torch.squeeze.html) | Squeezes `input` to remove all the dimenions with value `1`. |
| [`torch.unsqueeze(input, dim)`](https://pytorch.org/docs/1.9.1/generated/torch.unsqueeze.html) | Returns `input` with a dimension value of `1` added at `dim`. |
| [`torch.permute(input, dims)`](https://pytorch.org/docs/stable/generated/torch.permute.html) | Returns a *view* of the original `input` with its dimensions permuted (rearranged) to `dims`. |

Why do any of these?

Because deep learning models (neural networks) are all about manipulating tensors in some way. And because of the rules of matrix multiplication, if you've got shape mismatches, you'll run into errors. These methods help you make sure the right elements of your tensors are mixing with the right elements of other tensors.


In [322]:
# No of elements should remain same

In [323]:
x = torch.arange(1,10)
x

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [324]:
x.shape

torch.Size([9])

In [325]:
x.reshape(3,3)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [326]:
x

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [327]:
y = torch.rand(8,4)
y

tensor([[0.8643, 0.5919, 0.7483, 0.4759],
        [0.6945, 0.6318, 0.3488, 0.6021],
        [0.5678, 0.2791, 0.7283, 0.1858],
        [0.4350, 0.8956, 0.5706, 0.6664],
        [0.6840, 0.8941, 0.1689, 0.2513],
        [0.7443, 0.4160, 0.1105, 0.3843],
        [0.6247, 0.4382, 0.7152, 0.6605],
        [0.4538, 0.2856, 0.8886, 0.1439]])

In [328]:
y.reshape(4,2,4)

tensor([[[0.8643, 0.5919, 0.7483, 0.4759],
         [0.6945, 0.6318, 0.3488, 0.6021]],

        [[0.5678, 0.2791, 0.7283, 0.1858],
         [0.4350, 0.8956, 0.5706, 0.6664]],

        [[0.6840, 0.8941, 0.1689, 0.2513],
         [0.7443, 0.4160, 0.1105, 0.3843]],

        [[0.6247, 0.4382, 0.7152, 0.6605],
         [0.4538, 0.2856, 0.8886, 0.1439]]])

In [329]:
z = x.view(3,3)

In [330]:
z

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [331]:
z[0] = 51 # z is allocated in same meory as x.

In [332]:
x,z

(tensor([51, 51, 51,  4,  5,  6,  7,  8,  9]),
 tensor([[51, 51, 51],
         [ 4,  5,  6],
         [ 7,  8,  9]]))

In [333]:
x

tensor([51, 51, 51,  4,  5,  6,  7,  8,  9])

In [334]:
torch.stack([x,x,x],dim=1)

tensor([[51, 51, 51],
        [51, 51, 51],
        [51, 51, 51],
        [ 4,  4,  4],
        [ 5,  5,  5],
        [ 6,  6,  6],
        [ 7,  7,  7],
        [ 8,  8,  8],
        [ 9,  9,  9]])

In [335]:
torch.stack([x,x,x],dim=1).shape

torch.Size([9, 3])

In [336]:
x.shape

torch.Size([9])

In [337]:
torch.stack([x,x,x],dim=1).ndim

2

In [338]:
x.ndim

1

In [339]:
y

tensor([[0.8643, 0.5919, 0.7483, 0.4759],
        [0.6945, 0.6318, 0.3488, 0.6021],
        [0.5678, 0.2791, 0.7283, 0.1858],
        [0.4350, 0.8956, 0.5706, 0.6664],
        [0.6840, 0.8941, 0.1689, 0.2513],
        [0.7443, 0.4160, 0.1105, 0.3843],
        [0.6247, 0.4382, 0.7152, 0.6605],
        [0.4538, 0.2856, 0.8886, 0.1439]])

In [340]:
torch.stack([y,y,y],dim=1)

tensor([[[0.8643, 0.5919, 0.7483, 0.4759],
         [0.8643, 0.5919, 0.7483, 0.4759],
         [0.8643, 0.5919, 0.7483, 0.4759]],

        [[0.6945, 0.6318, 0.3488, 0.6021],
         [0.6945, 0.6318, 0.3488, 0.6021],
         [0.6945, 0.6318, 0.3488, 0.6021]],

        [[0.5678, 0.2791, 0.7283, 0.1858],
         [0.5678, 0.2791, 0.7283, 0.1858],
         [0.5678, 0.2791, 0.7283, 0.1858]],

        [[0.4350, 0.8956, 0.5706, 0.6664],
         [0.4350, 0.8956, 0.5706, 0.6664],
         [0.4350, 0.8956, 0.5706, 0.6664]],

        [[0.6840, 0.8941, 0.1689, 0.2513],
         [0.6840, 0.8941, 0.1689, 0.2513],
         [0.6840, 0.8941, 0.1689, 0.2513]],

        [[0.7443, 0.4160, 0.1105, 0.3843],
         [0.7443, 0.4160, 0.1105, 0.3843],
         [0.7443, 0.4160, 0.1105, 0.3843]],

        [[0.6247, 0.4382, 0.7152, 0.6605],
         [0.6247, 0.4382, 0.7152, 0.6605],
         [0.6247, 0.4382, 0.7152, 0.6605]],

        [[0.4538, 0.2856, 0.8886, 0.1439],
         [0.4538, 0.2856, 0.8886, 0.1439

In [341]:
torch.stack([y,y,y],dim=1).shape

torch.Size([8, 3, 4])

In [342]:
torch.stack([y,y,y],dim=0)

tensor([[[0.8643, 0.5919, 0.7483, 0.4759],
         [0.6945, 0.6318, 0.3488, 0.6021],
         [0.5678, 0.2791, 0.7283, 0.1858],
         [0.4350, 0.8956, 0.5706, 0.6664],
         [0.6840, 0.8941, 0.1689, 0.2513],
         [0.7443, 0.4160, 0.1105, 0.3843],
         [0.6247, 0.4382, 0.7152, 0.6605],
         [0.4538, 0.2856, 0.8886, 0.1439]],

        [[0.8643, 0.5919, 0.7483, 0.4759],
         [0.6945, 0.6318, 0.3488, 0.6021],
         [0.5678, 0.2791, 0.7283, 0.1858],
         [0.4350, 0.8956, 0.5706, 0.6664],
         [0.6840, 0.8941, 0.1689, 0.2513],
         [0.7443, 0.4160, 0.1105, 0.3843],
         [0.6247, 0.4382, 0.7152, 0.6605],
         [0.4538, 0.2856, 0.8886, 0.1439]],

        [[0.8643, 0.5919, 0.7483, 0.4759],
         [0.6945, 0.6318, 0.3488, 0.6021],
         [0.5678, 0.2791, 0.7283, 0.1858],
         [0.4350, 0.8956, 0.5706, 0.6664],
         [0.6840, 0.8941, 0.1689, 0.2513],
         [0.7443, 0.4160, 0.1105, 0.3843],
         [0.6247, 0.4382, 0.7152, 0.6605],
       

In [343]:
torch.stack([y,y,y],dim=0).shape

torch.Size([3, 8, 4])

In [344]:
y.shape

torch.Size([8, 4])

In [345]:
# So the as we stacked 3 tensors it would be added with an extra dimension

In [346]:
# squeezeing the tensor , it returns a tensor with all specified dimensions of input of size 1 removed.

In [347]:
Tensor_C = torch.arange(12,21)
Tensor_C

tensor([12, 13, 14, 15, 16, 17, 18, 19, 20])

In [348]:
Tensor_C.reshape(9,1)

tensor([[12],
        [13],
        [14],
        [15],
        [16],
        [17],
        [18],
        [19],
        [20]])

In [349]:
Tensor_C.reshape(9,1).shape

torch.Size([9, 1])

In [350]:
Tensor_C.shape

torch.Size([9])

In [351]:
Tensor_C.reshape(9,1).squeeze()

tensor([12, 13, 14, 15, 16, 17, 18, 19, 20])

In [352]:
Tensor_C.reshape(9,1).squeeze().shape

torch.Size([9])

In [353]:
tensor_x = torch.rand(2,1,3,1,4)
tensor_x

tensor([[[[[8.5118e-02, 3.0772e-01, 5.6678e-01, 7.9210e-01]],

          [[4.2841e-01, 3.5636e-01, 2.0901e-01, 8.7147e-01]],

          [[1.8773e-01, 9.6104e-01, 2.4166e-01, 8.4010e-01]]]],



        [[[[7.9907e-01, 6.5245e-01, 6.8737e-01, 5.8138e-01]],

          [[9.0998e-04, 1.9753e-01, 8.8357e-01, 7.3619e-01]],

          [[4.0335e-01, 5.0786e-01, 9.8973e-02, 1.9327e-01]]]]])

In [354]:
tensor_x_squeezed = tensor_x.squeeze()
tensor_x_squeezed

tensor([[[8.5118e-02, 3.0772e-01, 5.6678e-01, 7.9210e-01],
         [4.2841e-01, 3.5636e-01, 2.0901e-01, 8.7147e-01],
         [1.8773e-01, 9.6104e-01, 2.4166e-01, 8.4010e-01]],

        [[7.9907e-01, 6.5245e-01, 6.8737e-01, 5.8138e-01],
         [9.0998e-04, 1.9753e-01, 8.8357e-01, 7.3619e-01],
         [4.0335e-01, 5.0786e-01, 9.8973e-02, 1.9327e-01]]])

In [355]:
tensor_x_squeezed.shape # All the dims with dimension 1 got squeezed.

torch.Size([2, 3, 4])

In [356]:
tensor_y = torch.squeeze(tensor_x , 1)

In [357]:
tensor_y.shape

torch.Size([2, 3, 1, 4])

In [358]:
torch.squeeze(tensor_x , 0).shape # NO change , because at 0th dimension there was not 1 diemsnion

torch.Size([2, 1, 3, 1, 4])

In [359]:
# Tensor size - (2,4,2,1,3) 2 is 0th dimension , 4 is 1st dimension , 2 is 2nd dimension , 1 is 3rd dimesnion , 3 is 4th dimension and overall ndim is 5 , outher sq bracket is 0th dim and as we move inside the dim increases

In [360]:
torch.squeeze(tensor_x , 1).shape

torch.Size([2, 3, 1, 4])

In [361]:
torch.squeeze(tensor_x , 2).shape

torch.Size([2, 1, 3, 1, 4])

In [362]:
torch.squeeze(tensor_x , 3).shape

torch.Size([2, 1, 3, 4])

In [363]:
# unsqueeze , adds a dimension of 1 at specified dimension.
tensor_x.shape

torch.Size([2, 1, 3, 1, 4])

In [364]:
tensor_x.unsqueeze(0).shape

torch.Size([1, 2, 1, 3, 1, 4])

In [365]:
torch.permute(tensor_x , (1,0,2,3,4)).shape

torch.Size([1, 2, 3, 1, 4])

In [366]:
torch.permute(tensor_x , (1,0,2,3,4))

tensor([[[[[8.5118e-02, 3.0772e-01, 5.6678e-01, 7.9210e-01]],

          [[4.2841e-01, 3.5636e-01, 2.0901e-01, 8.7147e-01]],

          [[1.8773e-01, 9.6104e-01, 2.4166e-01, 8.4010e-01]]],


         [[[7.9907e-01, 6.5245e-01, 6.8737e-01, 5.8138e-01]],

          [[9.0998e-04, 1.9753e-01, 8.8357e-01, 7.3619e-01]],

          [[4.0335e-01, 5.0786e-01, 9.8973e-02, 1.9327e-01]]]]])

In [367]:
torch.permute(tensor_x , (1,0,2,3,4))[0][0][0][0][0] = 1

In [368]:
tensor_x # the permute shares same memory with original tensor , so change in permuted will change the original

tensor([[[[[1.0000e+00, 3.0772e-01, 5.6678e-01, 7.9210e-01]],

          [[4.2841e-01, 3.5636e-01, 2.0901e-01, 8.7147e-01]],

          [[1.8773e-01, 9.6104e-01, 2.4166e-01, 8.4010e-01]]]],



        [[[[7.9907e-01, 6.5245e-01, 6.8737e-01, 5.8138e-01]],

          [[9.0998e-04, 1.9753e-01, 8.8357e-01, 7.3619e-01]],

          [[4.0335e-01, 5.0786e-01, 9.8973e-02, 1.9327e-01]]]]])

In [369]:
tensor_x.shape

torch.Size([2, 1, 3, 1, 4])

In [370]:
# Indeixng
z = torch.randint(0, 100 , (4, 3, 3), dtype=torch.int32)
z

tensor([[[13, 23, 28],
         [89, 56,  9],
         [72, 68, 84]],

        [[10, 66, 71],
         [53, 10, 22],
         [ 6, 91, 97]],

        [[79, 96, 68],
         [86, 35, 47],
         [59, 93,  8]],

        [[ 3, 15, 64],
         [30, 79, 22],
         [30, 21,  1]]], dtype=torch.int32)

In [371]:
# You can use ":" to select "all" of a target dimension

In [372]:
z[1:0]

tensor([], size=(0, 3, 3), dtype=torch.int32)

In [373]:
# For now not able to understand ":" this slicing.


PyTorch tensors & NumPy
Since NumPy is a popular Python numerical computing library, PyTorch has functionality to interact with it nicely.

The two main methods you'll want to use for NumPy to PyTorch (and back again) are:

torch.from_numpy(ndarray) - NumPy array -> PyTorch tensor.
torch.Tensor.numpy() - PyTorch tensor -> NumPy array.

In [374]:
array = np.arange(1.0, 8.0)
array

array([1., 2., 3., 4., 5., 6., 7.])

In [375]:
array.dtype

dtype('float64')

In [376]:
tensor = torch.from_numpy(array) # Altough the default data type of pytorch is float 32 , but for numpy is float 64 so while converting numpy to pytorch the data type we got was of default numpy
tensor

tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64)

In [377]:
tensor.type(torch.float32)

tensor([1., 2., 3., 4., 5., 6., 7.])

In [378]:
array = array + 1
array

array([2., 3., 4., 5., 6., 7., 8.])

In [379]:
tensor # It's a new copy

tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64)

In [380]:
x = torch.rand(3,4)

In [381]:
numpy_array = torch.Tensor.numpy(x)

In [382]:
numpy_array

array([[0.45541793, 0.16880685, 0.82999337, 0.88572425],
       [0.48422706, 0.95326734, 0.5533615 , 0.25066   ],
       [0.0722214 , 0.53053415, 0.37226623, 0.76096916]], dtype=float32)

In [383]:
x = x + 2

In [384]:
x

tensor([[2.4554, 2.1688, 2.8300, 2.8857],
        [2.4842, 2.9533, 2.5534, 2.2507],
        [2.0722, 2.5305, 2.3723, 2.7610]])

In [385]:
numpy_array

array([[0.45541793, 0.16880685, 0.82999337, 0.88572425],
       [0.48422706, 0.95326734, 0.5533615 , 0.25066   ],
       [0.0722214 , 0.53053415, 0.37226623, 0.76096916]], dtype=float32)

In [386]:
torch.cuda.is_available()

False

In [387]:
# Set device type
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cpu'

In [388]:
# Count number of devices
torch.cuda.device_count()

0